version: '3.8'
services:
  hazelcast-member1:
    image: hazelcast/hazelcast:5.3.6
    environment:
      - HZ_NETWORK_PUBLICADDRESS=hazelcast-member1:5701
      - HZ_CLUSTERNAME=hazel_claster
    networks:
      - hazelcast-network
    ports:
      - "5701:5701"

  hazelcast-member2:
    image: hazelcast/hazelcast:5.3.6
    environment:
      - HZ_NETWORK_PUBLICADDRESS=hazelcast-member2:5701
      - HZ_CLUSTERNAME=hazel_claster
    networks:
      - hazelcast-network
    ports:
      - "5702:5701"

  hazelcast-member3:
    image: hazelcast/hazelcast:5.3.6
    environment:
      - HZ_NETWORK_PUBLICADDRESS=hazelcast-member3:5701
      - HZ_CLUSTERNAME=hazel_claster
    networks:
      - hazelcast-network
    ports:
      - "5703:5701"

  management-center:
    image: hazelcast/management-center:5.3
    environment:
      - MC_HTTP_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - hazelcast-network

networks:
  hazelcast-network:
    driver: bridge
